---
author: Clement Guillo
title: Data Scientist
format:
  classic-cv-pdf: default
cvfooter:
  left: ""
  right: ""
cvcolor: 58748F #without `#`
cvfont: raleway #texlive fonts like raleway,fetamont,gillius,comfortaa
cvmeta:
  - title: Status
    left: Head of Statistical Service at INSEE Antilles-Guyane
    right: Guadeloupe, France
  - title: Field
    left: Data Science, Statistical Methods, Spatial Analysis 
    right: /in/clgui23
  - left:  +33 6 19 93 25 36
    right: github.com/clement2323  
execute:
  echo: false
---

```{r}

#| label: cvevents
cvevents <- function(tbl, when, what, where, details) {

    command_start <- "\\cvevent"

    res <- paste0(
        command_start, "{", tbl[[when]], "}", 
        "{", tbl[[what]], "}",
        "{", tbl[[where]], "}")
    
    tbl[[details]] <- sapply(tbl[[details]], function(x) paste0("{", x, "}", collapse = ","))
    res <- paste0(res, "{",tbl[[details]],"}")

    cat(res, sep = "\n")
}

cvskills <- function(tbl, category, skills) {
    command_start <- "\\cvskills"

    # Agrège les skills par catégorie
    unique_categories <- unique(tbl[[category]])
    
    res <- sapply(unique_categories, function(cat) {
        skills_list <- tbl[tbl[[category]] == cat, ][[skills]]
        skills_formatted <- paste0("{", paste(skills_list, collapse = "},{"), "}")
        
        paste0(
            command_start,
            "{", cat, "}",
            "{", skills_formatted, "}"
        )
    })

    cat(res, sep = "\n")
}
```



# Profile

Data Scientist with extensive experience in spatial statistics and deep learning applications, seeking position in data-science. Proven track record in implementing large-scale data processing solutions and leading cross-functional teams.

# Professional Experience

```{r}
#| label: experience
#| output: asis
tibble::tribble(
    ~role, ~institution, ~dates, ~details, ~tasks,
    "Head of Statistical Service", "INSEE - Caribbean", "09/2023 - Present",
    "Guadeloupe, France", c(
        "Developed and applied deep learning algorithms for population census by processing thousands of satellite images of overseas territories (including Réunion and Mayotte). Delivered a trained segmentation model based on these images and deployed the results through an application to support population census (RP) estimates.",
        "Streamlined and automated production practices across three territories (Guadeloupe, Martinique, Guyane), coordinating efforts across diverse teams.",
        "Managed INSEE agents across three territories (Guadeloupe, Martinique, Guyane), overseeing the coordination and execution of on-the-ground survey operations."
        "Designed an R training program, aimed at improving the skills of 20 Caribbean area agents."
    ),
    "Head of Spatial Statistics Methods and Data Protection Methods (Statistical Disclosure Control).", "INSEE - Paris", "09/2019 - 08/2023",
    "Paris, France", c(
        "Managed a team of 4 members and supervised 3 interns focused on satellite image analysis.",
        "Led the development of deep learning models achieving high accuracy in satellite image segmentation for land cover detection.",
        "Directed the redesign of a georeferencing system impacting 30 million address records.",
        "Designed and implemented an algorithm to ensure the confidentiality of gridded data across the entirety of France, addressing differentiation attacks and enabling large-scale data dissemination.",
        "Supervised statistical disclosure control for 20 public statistics surveys conducted annually by INSEE.",
    ),
    "Data Science Intern", "WESTAT - Rockville MD, USA", "07/2019 - 09/2019",
    "Rockville, Maryland, USA", c(
        "Developed innovative estimation methods for rare events using Zero-Inflated Poisson Models.",
        "Analyzed large-scale imbalanced datasets with more than 100,000 observations.",
        "Implemented an EM algorithm, improving prediction accuracy by"
    ),
    "Household Survey Manager", "INSEE - Paris", "09/2017 - 08/2018",
    "Paris, France", c(
        "Contributed to the redesign of the Master Sample, representing the nationwide household sampling framework for INSEE surveys. Conducted large-scale sampling", "Simulations for the entirety of France using advanced sampling methods. The proposed solution, now deployed at INSEE, directly impacts the work of nearly 700 field interviewers.", 
        "Worked closely with a team of five statisticians to parallelize processing workflows and analyze results, including variance estimation"
    ),
    "Financial Institutions Account Manager", "INSEE - Paris", "09/2014 - 08/2017",
    "Paris, France", c(
        "Proposed and implemented a modernization of the national accounts construction process for financial institutions, which operates iteratively.",
        "Optimized the iteration time, reducing it from 40 minutes to just 2 minutes per cycle, significantly improving efficiency."
        "Produced quarterly statistical reports for national accounts."
    )
) |>
    cvevents(when = "dates", what = "role", where = "institution", details = "tasks")

```

# Education

```{r}
#| label: education
#| output: asis
tibble::tribble(
    ~degree, ~loc, ~dates, ~details,
    "Master of Research in Mathematics, Vision and Learning (MVA)", "ENS - Paris, France", "09/2019 - 08/2020", c(
        "Highest Honors",
        "Specialized in machine learning and computer vision",
        "Research thesis on statistical models for database fusion",
        "Deep learning, Reinforcement learning"
    ),
    
    "Statistical Methodology Master", "ENSAE - Paris, France", "09/2018 - 08/2020", c(
        "Highest Honors",
        "Advanced coursework in statistical methods and data analysis",
        "Time series analysis, sampling survey methodology"
    ),
    
    "Engineering Degree in Statistics and p", "ENSAI - Rennes, France", "09/2011 - 08/2013", c(
        "Core curriculum in statistical methods and programming",
        "Specialized in data processing and analysis",
        "Teaching Assistant for Statistics and Python courses"
    )
) |>
    cvevents(when = "dates", what = "degree", where = "loc", details = "details")
```

# Projects

```{r}
#| label: Projects & Achievements
#| output: asis
tibble::tribble(
    ~project, ~institution, ~dates, ~details,
    "Automated Satellite Image Analysis", "INSEE - Paris", "2023", c(
        "Developed a full pipeline to detect building locations from Pleiades satellite images.",
        "Trained SegFormer segmentation models for high-accuracy building detection.",
        "Integrated a containerized workflow with Kubernetes (Argo Workflows and ArgoCD).",
        "Built interactive web applications with React (Observable) and GeoServer for result visualization.",
        "Tracked experiments using MLFlow and hosted the solution on INSEE's Kubernetes cluster."
    ),
    
    "Automated Study Reporting System (BoutaDe)", "INSEE - Paris", "2021 - 2023", c(
        "Designed and implemented a comprehensive pipeline for automating study report production using R.",
        "Developed and published the 'BoutaDe' R package on GitHub, enabling rapid, reproducible reporting workflows.",
        "Automated content generation with ChatGPT, dynamically tailoring text to outputs, metadata, and target audiences.",
        "Adapted reports for specific user roles (e.g., adolescents, adults, humorous tones) using metadata-driven customization.",
        "Integrated advanced visualizations with ggplot2 and interactive dashboards using Shiny.",
        "Streamlined collaboration and reproducibility through Git-based version control and Kubernetes-based deployments."
    ),
    
    "Research Project", "ENSAE engineer school - PARIS", "2019 - 2020", c(
        "Developed novel statistical models for database fusion.",
        "Published findings in departmental research journal.",
        "Presented results at student research symposium."
    ),
    
    "Hackathon Winner", "EY Paris", "2018", c(
        "Led team of 4 to victory among 50 \\% competing teams.",
        "Developed machine learning model with 85 \\% prediction accuracy.",
        "Implemented solution using Random Forests in Python."
    ,
    "Master’s Thesis: Statistical Methodology for Smoothing Insurance Claims", "ENSAI engineer school - PARIS", "2020", c(
        "Developed advanced smoothing methods for insurance claims data using Kalman Filters.",
        "Proposed innovative approaches for time-series modeling and forecasting of indemnities.",
        "Presented findings to faculty and insurance industry professionals."
    )
) |>
    cvevents(when = "dates", what = "project", where = "institution", details = "details")

```

# Skills
```{r}
#| label: skills
#| output: asis
#| 
# Exemple de données
#| label: skills
#| output: asis

skills_data <- tibble::tribble(
  ~category,      ~skills,
  "Languages",    "French (Native)",
  "Languages",    "English (B2) (TOEIC 895/990)",
  "Languages",    "Espagnol",
  "Programming",  "Python (Pytorch, Scipy), R (Expert), SQL (Advanced)",
  "Programming",  "Docker, kubernetes, MLOPS",
  "Programming",  "Web Development, Javascript React, NextJS"
)

# Générer le LaTeX
skills_data |>
  cvskills(category = "category", skills = "skills")

```


# Interests and activities
```{r}
#| label: activities
#| output: asis

interest_data <- tibble::tribble(
  ~category,      ~skills,
  "Sport",    "Surf",
  "Sport",    "Chess",
  "Music",  "Guitar",
)

# Générer le LaTeX
interest_data |>
  cvskills(category = "category", skills = "skills")

```